PROGRAM MAIN
  USE KEYS, ONLY: ACTION,NTRIALS,NTYPE,NPART,MAXNPART,DOFUSION
  USE PARTICLEUTILS, ONLY: PARTICLE,PARTICLEGROUP,PARTICLEPARAMS,&
                            SETUPPARTICLEPARAMS,CLEANUPPARTICLEGROUP,CLEANUPPARTICLEPARAMS

  IMPLICIT NONE
  DOUBLE PRECISION :: T1,T2
  TYPE(PARTICLEGROUP), POINTER :: GROUPLIST(:)
  TYPE(PARTICLEGROUP), POINTER :: PGROUP
  TYPE(PARTICLEPARAMS), TARGET :: PARTPARAMS
  TYPE(PARTICLEPARAMS), POINTER :: PARAMP

  INTEGER :: TRC

  ! start timer
  CALL CPU_TIME(T1)

  ! parse free format input file
  CALL READKEY
  PARAMP=>PARTPARAMS
  CALL SETUPPARTICLEPARAMS(PARAMP)
  
  ! initialize particle arrays
  ALLOCATE(GROUPLIST(NTRIALS))

  SELECT CASE(ACTION)
    CASE('RUNDYNAMICS')
      
      !insert code to run requested action
      CALL FUSIONDRIVER(GROUPLIST,PARAMP,NTRIALS,DOFUSION)

    CASE DEFAULT
    PRINT*, 'ERROR IN MAIN: unidentified action', ACTION
    STOP 1
  END SELECT

  DO TRC = 1,NTRIALS
    PGROUP=>GROUPLIST(TRC)
    CALL CLEANUPPARTICLEGROUP(PGROUP)
  END DO
  DEALLOCATE(GROUPLIST)
  
  CALL CLEANUPPARTICLEPARAMS(PARAMP)
  
  CALL CPU_TIME(T2)
  PRINT*,''
  PRINT '(A8,F12.3,A1)','Runtime:', T2-T1,'s'

  CONTAINS  
    SUBROUTINE FUSIONDRIVER(GROUPLIST,PARAMP,NTRIALS,DOFUSION)
    ! run fusion dynamics
      USE PARTDYNAMICS, ONLY: TRANSPORTSIM
      USE PARTICLEUTILS, ONLY: MAKEPARTICLE,SETUPPARTICLEGROUP
      
      IMPLICIT NONE

      INTEGER, INTENT(IN) :: NTRIALS
      TYPE(PARTICLEGROUP), TARGET :: GROUPLIST(NTRIALS)
      TYPE(PARTICLEGROUP), POINTER :: PGROUP
      TYPE(PARTICLE), POINTER :: PLIST(:)
      TYPE(PARTICLE), POINTER :: PARTP
      TYPE(PARTICLEPARAMS), POINTER :: PARAMP
      LOGICAL, INTENT(IN) :: DOFUSION
      INTEGER :: TC,PID,NC,CC
      
      DO TC = 1,NTRIALS
        PGROUP=>GROUPLIST(TC)
        PLIST=>PGROUP%PLIST
        ALLOCATE(PLIST(PARAMP%MAXNPART))
        PID = 1
        DO NC = 1,NTYPE
          DO CC = 1,NPART(NC)
            PARTP=>PLIST(PID)
            ! PRINT*, 'TESTX2',PID,PARTP%NPROT
            CALL MAKEPARTICLE(PARTP,PID,NC,PARAMP,CANFUSE=.TRUE.)
            
            
            PID = PID+1
            IF(PID.GE.PARAMP%MAXNPART) THEN
              PRINT*, 'ERROR: too many particles'
              STOP 1
            END IF
          END DO
        END DO
        CALL SETUPPARTICLEGROUP(PGROUP,NPART,PLIST)
      END DO
     
      CALL TRANSPORTSIM(GROUPLIST,PARAMP,NTRIALS,DOFUSION)
    END SUBROUTINE FUSIONDRIVER

END PROGRAM MAIN